apiVersion: apps/v1
kind: ReplicationController
metadata:
  labels:
    name: java-app
  name: java-web-app-test  
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: java-app
    spec:
      containers:
        - name: java-app
          image: radhakrishna4687/java-test-web-app:0.4
          ports:
            - containerPort: 8080
              name: java-app
---            
#node port
apiVersion: v1
kind: Service
metadata:
  labels:
    name: java-app
  name: java-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8089
  selector:
    name: java-app  
